#!/usr/bin/env node
/**
 * Generate complete SQL migration from category_system.json
 * Run this script to create the full migration with all data insertions
 * 
 * Usage: node generateCategorySQLe.js
 */

const fs = require('fs');
const path = require('path');

const JSON_FILE = path.join(__dirname, '../../categories/category_system.json');
const OUTPUT_FILE = path.join(__dirname, '../migrations/migration_002_data.sql');

console.log('Reading category system JSON...');
console.log('Path:', JSON_FILE);
const categorySystem = JSON.parse(fs.readFileSync(JSON_FILE, 'utf-8'));


let sql = `-- Category System Full Data Migration
-- Generated automatically from category_system.json
-- DO NOT EDIT THIS FILE MANUALLY

`;

// Generate department inserts
console.log('Generating department inserts...');
const departments = categorySystem.departments;

for (const dept of departments) {
  sql += `INSERT INTO departments (id, name_tr, name_en, color_code, icon) VALUES\n`;
  sql += `  (${dept.id}, '${escapeSql(dept.name)}', '${escapeSql(dept.name_en)}', '${dept.color}', '${dept.icon}');\n`;
}

sql += '\n-- Insert Categories\n';

// Generate category inserts
console.log('Generating category inserts...');
for (const dept of departments) {
  for (const cat of dept.categories) {
    sql += `INSERT INTO categories (id, department_id, name_tr, name_en, color_code) VALUES\n`;
    sql += `  (${cat.id}, ${dept.id}, '${escapeSql(cat.name)}', '${escapeSql(cat.name_en)}', '${cat.color}');\n`;
  }
}

sql += '\n-- Insert Subcategories\n';

// Generate subcategory inserts
console.log('Generating subcategory inserts...');
for (const dept of departments) {
  for (const cat of dept.categories) {
    for (const subcat of cat.subcategories) {
      sql += `INSERT INTO subcategories (id, category_id, name_tr, name_en, color_code) VALUES\n`;
      sql += `  (${subcat.id}, ${cat.id}, '${escapeSql(subcat.name)}', '${escapeSql(subcat.name_en)}', '${subcat.color}');\n`;
    }
  }
}

sql += '\n-- Insert Item Groups\n';

// Generate item group inserts
console.log('Generating item group inserts...');
for (const dept of departments) {
  for (const cat of dept.categories) {
    for (const subcat of cat.subcategories) {
      if (subcat.item_groups && subcat.item_groups.length > 0) {
        for (const item of subcat.item_groups) {
          sql += `INSERT INTO item_groups (subcategory_id, name_tr) VALUES\n`;
          sql += `  (${subcat.id}, '${escapeSql(item)}');\n`;
        }
      }
    }
  }
}

// Write to file
console.log(`Writing SQL to: ${OUTPUT_FILE}`);
fs.writeFileSync(OUTPUT_FILE, sql, 'utf-8');

console.log('✅ SQL migration generated successfully!');
console.log(`📊 Statistics:`);
console.log(`  - Departments: ${departments.length}`);
console.log(`  - Categories: ${departments.reduce((sum, d) => sum + d.categories.length, 0)}`);
console.log(`  - Subcategories: ${departments.reduce((sum, d) => sum + d.categories.reduce((s, c) => s + c.subcategories.length, 0), 0)}`);
console.log(`  - Item Groups: ${countItemGroups(departments)}`);

/**
 * Escape SQL strings to prevent injection
 */
function escapeSql(str) {
  if (!str) return '';
  return str.replace(/'/g, "''");
}

/**
 * Count total item groups
 */
function countItemGroups(departments) {
  let count = 0;
  for (const dept of departments) {
    for (const cat of dept.categories) {
      for (const subcat of cat.subcategories) {
        if (subcat.item_groups) {
          count += subcat.item_groups.length;
        }
      }
    }
  }
  return count;
}
